//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace snpptt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int ID { get; set; }
        public string URL { get; set; }
        public int WindowWidth { get; set; }
        public int WindowHeight { get; set; }
        public int ScrollPosition { get; set; }
        public int SnipX { get; set; }
        public int SnipY { get; set; }
        public int SnipWidth { get; set; }
        public int SnipHeight { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
